---

- name: Create logstash configuration file
  template: src=logstash.conf.j2 dest={{ logstash_conf_dir }}/mysql.conf owner=root group=root mode=0644
  notify:
    - restart logstash
  when: mysql_server_use_logstash
  tags:
    - logstash
    - mysql
